####### INSTRUCTION #######
# this script is specifically for the data generated by MPI code.
# to use it, first input the file name in the variable "file_name",
# and then input the number of processors used in the variable "num_of_proc".
# Then, type "python contour_plot_mpi.py" in the terminal


from matplotlib.pyplot import *
from numpy import *


num_of_proc = 16

file_name = ['/Users/hty/Google Drive/grad course work/apc524 software engineering/hw4/local/apc524_hw4/heat_mpi_128_%s.out'%(i) for i in range (num_of_proc)]

Readfiles=[file(file_name[i]) for i in range (num_of_proc) ]

interm_syn = [array(Readfiles[i].readlines()) for i in range (shape(Readfiles)[0])]

''' remember to set start line number here '''
interm1_syn =[ [str.split(interm_syn[j][i]) for i in range(1,shape(interm_syn[j])[0])] for j in range (shape(interm_syn)[0])]

xy= [[[float(interm1_syn[k][j][i]) for j in range (0,shape(interm1_syn[k])[0])]for i in range (shape(interm1_syn[k][0])[0]) ] for k in range (shape(interm_syn)[0])]


a = xy[0]

for i in range (num_of_proc-1):
    a=concatenate ((a,xy[i+1]),axis = 0)

close('all')
f = figure()
imshow(transpose(a))

colorbar()
title('MPI (Grid size = 128)')
show()
# f.savefig('mpi_128.pdf')
